// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldContentMarkdown holds the string denoting the content_markdown field in the database.
	FieldContentMarkdown = "content_markdown"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldPublished holds the string denoting the published field in the database.
	FieldPublished = "published"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// FieldRepositoryURL holds the string denoting the repository_url field in the database.
	FieldRepositoryURL = "repository_url"
	// FieldLiveURL holds the string denoting the live_url field in the database.
	FieldLiveURL = "live_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTechnologies holds the string denoting the technologies edge name in mutations.
	EdgeTechnologies = "technologies"
	// EdgeTechnologyLinks holds the string denoting the technology_links edge name in mutations.
	EdgeTechnologyLinks = "technology_links"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// TechnologiesTable is the table that holds the technologies relation/edge. The primary key declared below.
	TechnologiesTable = "project_technologies"
	// TechnologiesInverseTable is the table name for the Technology entity.
	// It exists in this package in order to avoid circular dependency with the "technology" package.
	TechnologiesInverseTable = "technologies"
	// TechnologyLinksTable is the table that holds the technology_links relation/edge.
	TechnologyLinksTable = "project_technologies"
	// TechnologyLinksInverseTable is the table name for the ProjectTechnology entity.
	// It exists in this package in order to avoid circular dependency with the "projecttechnology" package.
	TechnologyLinksInverseTable = "project_technologies"
	// TechnologyLinksColumn is the table column denoting the technology_links relation/edge.
	TechnologyLinksColumn = "project_id"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldTitle,
	FieldSummary,
	FieldPeriod,
	FieldRole,
	FieldContentMarkdown,
	FieldFeatured,
	FieldPublished,
	FieldDisplayOrder,
	FieldRepositoryURL,
	FieldLiveURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TechnologiesPrimaryKey and TechnologiesColumn2 are the table columns denoting the
	// primary key for the technologies relation (M2M).
	TechnologiesPrimaryKey = []string{"project_id", "technology_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultPublished holds the default value on creation for the "published" field.
	DefaultPublished bool
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
	// DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	DisplayOrderValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByContentMarkdown orders the results by the content_markdown field.
func ByContentMarkdown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentMarkdown, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// ByPublished orders the results by the published field.
func ByPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublished, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// ByRepositoryURL orders the results by the repository_url field.
func ByRepositoryURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryURL, opts...).ToFunc()
}

// ByLiveURL orders the results by the live_url field.
func ByLiveURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiveURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTechnologiesCount orders the results by technologies count.
func ByTechnologiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTechnologiesStep(), opts...)
	}
}

// ByTechnologies orders the results by technologies terms.
func ByTechnologies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechnologiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTechnologyLinksCount orders the results by technology_links count.
func ByTechnologyLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTechnologyLinksStep(), opts...)
	}
}

// ByTechnologyLinks orders the results by technology_links terms.
func ByTechnologyLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechnologyLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTechnologiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TechnologiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TechnologiesTable, TechnologiesPrimaryKey...),
	)
}
func newTechnologyLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TechnologyLinksInverseTable, TechnologyLinksColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, TechnologyLinksTable, TechnologyLinksColumn),
	)
}
