// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectTechnology is the client for interacting with the ProjectTechnology builders.
	ProjectTechnology *ProjectTechnologyClient
	// Technology is the client for interacting with the Technology builders.
	Technology *TechnologyClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Project = NewProjectClient(c.config)
	c.ProjectTechnology = NewProjectTechnologyClient(c.config)
	c.Technology = NewTechnologyClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Project:           NewProjectClient(cfg),
		ProjectTechnology: NewProjectTechnologyClient(cfg),
		Technology:        NewTechnologyClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Project:           NewProjectClient(cfg),
		ProjectTechnology: NewProjectTechnologyClient(cfg),
		Technology:        NewTechnologyClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Project.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Project.Use(hooks...)
	c.ProjectTechnology.Use(hooks...)
	c.Technology.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Project.Intercept(interceptors...)
	c.ProjectTechnology.Intercept(interceptors...)
	c.Technology.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *ProjectTechnologyMutation:
		return c.ProjectTechnology.mutate(ctx, m)
	case *TechnologyMutation:
		return c.Technology.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id uuid.UUID) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id uuid.UUID) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id uuid.UUID) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id uuid.UUID) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTechnologies queries the technologies edge of a Project.
func (c *ProjectClient) QueryTechnologies(_m *Project) *TechnologyQuery {
	query := (&TechnologyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(technology.Table, technology.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, project.TechnologiesTable, project.TechnologiesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTechnologyLinks queries the technology_links edge of a Project.
func (c *ProjectClient) QueryTechnologyLinks(_m *Project) *ProjectTechnologyQuery {
	query := (&ProjectTechnologyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(projecttechnology.Table, projecttechnology.ProjectColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, project.TechnologyLinksTable, project.TechnologyLinksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// ProjectTechnologyClient is a client for the ProjectTechnology schema.
type ProjectTechnologyClient struct {
	config
}

// NewProjectTechnologyClient returns a client for the ProjectTechnology from the given config.
func NewProjectTechnologyClient(c config) *ProjectTechnologyClient {
	return &ProjectTechnologyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projecttechnology.Hooks(f(g(h())))`.
func (c *ProjectTechnologyClient) Use(hooks ...Hook) {
	c.hooks.ProjectTechnology = append(c.hooks.ProjectTechnology, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projecttechnology.Intercept(f(g(h())))`.
func (c *ProjectTechnologyClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectTechnology = append(c.inters.ProjectTechnology, interceptors...)
}

// Create returns a builder for creating a ProjectTechnology entity.
func (c *ProjectTechnologyClient) Create() *ProjectTechnologyCreate {
	mutation := newProjectTechnologyMutation(c.config, OpCreate)
	return &ProjectTechnologyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectTechnology entities.
func (c *ProjectTechnologyClient) CreateBulk(builders ...*ProjectTechnologyCreate) *ProjectTechnologyCreateBulk {
	return &ProjectTechnologyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectTechnologyClient) MapCreateBulk(slice any, setFunc func(*ProjectTechnologyCreate, int)) *ProjectTechnologyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectTechnologyCreateBulk{err: fmt.Errorf("calling to ProjectTechnologyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectTechnologyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectTechnologyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectTechnology.
func (c *ProjectTechnologyClient) Update() *ProjectTechnologyUpdate {
	mutation := newProjectTechnologyMutation(c.config, OpUpdate)
	return &ProjectTechnologyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectTechnologyClient) UpdateOne(_m *ProjectTechnology) *ProjectTechnologyUpdateOne {
	mutation := newProjectTechnologyMutation(c.config, OpUpdateOne)
	mutation.project = &_m.ProjectID
	mutation.technology = &_m.TechnologyID
	return &ProjectTechnologyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectTechnology.
func (c *ProjectTechnologyClient) Delete() *ProjectTechnologyDelete {
	mutation := newProjectTechnologyMutation(c.config, OpDelete)
	return &ProjectTechnologyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for ProjectTechnology.
func (c *ProjectTechnologyClient) Query() *ProjectTechnologyQuery {
	return &ProjectTechnologyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectTechnology},
		inters: c.Interceptors(),
	}
}

// QueryProject queries the project edge of a ProjectTechnology.
func (c *ProjectTechnologyClient) QueryProject(_m *ProjectTechnology) *ProjectQuery {
	return c.Query().
		Where(projecttechnology.ProjectID(_m.ProjectID), projecttechnology.TechnologyID(_m.TechnologyID)).
		QueryProject()
}

// QueryTechnology queries the technology edge of a ProjectTechnology.
func (c *ProjectTechnologyClient) QueryTechnology(_m *ProjectTechnology) *TechnologyQuery {
	return c.Query().
		Where(projecttechnology.ProjectID(_m.ProjectID), projecttechnology.TechnologyID(_m.TechnologyID)).
		QueryTechnology()
}

// Hooks returns the client hooks.
func (c *ProjectTechnologyClient) Hooks() []Hook {
	return c.hooks.ProjectTechnology
}

// Interceptors returns the client interceptors.
func (c *ProjectTechnologyClient) Interceptors() []Interceptor {
	return c.inters.ProjectTechnology
}

func (c *ProjectTechnologyClient) mutate(ctx context.Context, m *ProjectTechnologyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectTechnologyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectTechnologyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectTechnologyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectTechnologyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProjectTechnology mutation op: %q", m.Op())
	}
}

// TechnologyClient is a client for the Technology schema.
type TechnologyClient struct {
	config
}

// NewTechnologyClient returns a client for the Technology from the given config.
func NewTechnologyClient(c config) *TechnologyClient {
	return &TechnologyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `technology.Hooks(f(g(h())))`.
func (c *TechnologyClient) Use(hooks ...Hook) {
	c.hooks.Technology = append(c.hooks.Technology, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `technology.Intercept(f(g(h())))`.
func (c *TechnologyClient) Intercept(interceptors ...Interceptor) {
	c.inters.Technology = append(c.inters.Technology, interceptors...)
}

// Create returns a builder for creating a Technology entity.
func (c *TechnologyClient) Create() *TechnologyCreate {
	mutation := newTechnologyMutation(c.config, OpCreate)
	return &TechnologyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Technology entities.
func (c *TechnologyClient) CreateBulk(builders ...*TechnologyCreate) *TechnologyCreateBulk {
	return &TechnologyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TechnologyClient) MapCreateBulk(slice any, setFunc func(*TechnologyCreate, int)) *TechnologyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TechnologyCreateBulk{err: fmt.Errorf("calling to TechnologyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TechnologyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TechnologyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Technology.
func (c *TechnologyClient) Update() *TechnologyUpdate {
	mutation := newTechnologyMutation(c.config, OpUpdate)
	return &TechnologyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TechnologyClient) UpdateOne(_m *Technology) *TechnologyUpdateOne {
	mutation := newTechnologyMutation(c.config, OpUpdateOne, withTechnology(_m))
	return &TechnologyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TechnologyClient) UpdateOneID(id uuid.UUID) *TechnologyUpdateOne {
	mutation := newTechnologyMutation(c.config, OpUpdateOne, withTechnologyID(id))
	return &TechnologyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Technology.
func (c *TechnologyClient) Delete() *TechnologyDelete {
	mutation := newTechnologyMutation(c.config, OpDelete)
	return &TechnologyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TechnologyClient) DeleteOne(_m *Technology) *TechnologyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TechnologyClient) DeleteOneID(id uuid.UUID) *TechnologyDeleteOne {
	builder := c.Delete().Where(technology.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TechnologyDeleteOne{builder}
}

// Query returns a query builder for Technology.
func (c *TechnologyClient) Query() *TechnologyQuery {
	return &TechnologyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTechnology},
		inters: c.Interceptors(),
	}
}

// Get returns a Technology entity by its id.
func (c *TechnologyClient) Get(ctx context.Context, id uuid.UUID) (*Technology, error) {
	return c.Query().Where(technology.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TechnologyClient) GetX(ctx context.Context, id uuid.UUID) *Technology {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProjects queries the projects edge of a Technology.
func (c *TechnologyClient) QueryProjects(_m *Technology) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(technology.Table, technology.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, technology.ProjectsTable, technology.ProjectsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProjectLinks queries the project_links edge of a Technology.
func (c *TechnologyClient) QueryProjectLinks(_m *Technology) *ProjectTechnologyQuery {
	query := (&ProjectTechnologyClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(technology.Table, technology.FieldID, id),
			sqlgraph.To(projecttechnology.Table, projecttechnology.TechnologyColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, technology.ProjectLinksTable, technology.ProjectLinksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TechnologyClient) Hooks() []Hook {
	return c.hooks.Technology
}

// Interceptors returns the client interceptors.
func (c *TechnologyClient) Interceptors() []Interceptor {
	return c.inters.Technology
}

func (c *TechnologyClient) mutate(ctx context.Context, m *TechnologyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TechnologyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TechnologyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TechnologyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TechnologyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Technology mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Project, ProjectTechnology, Technology []ent.Hook
	}
	inters struct {
		Project, ProjectTechnology, Technology []ent.Interceptor
	}
)
