// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSlug sets the "slug" field.
func (_c *ProjectCreate) SetSlug(v string) *ProjectCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ProjectCreate) SetTitle(v string) *ProjectCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ProjectCreate) SetSummary(v string) *ProjectCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *ProjectCreate) SetPeriod(v string) *ProjectCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ProjectCreate) SetRole(v string) *ProjectCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContentMarkdown sets the "content_markdown" field.
func (_c *ProjectCreate) SetContentMarkdown(v string) *ProjectCreate {
	_c.mutation.SetContentMarkdown(v)
	return _c
}

// SetFeatured sets the "featured" field.
func (_c *ProjectCreate) SetFeatured(v bool) *ProjectCreate {
	_c.mutation.SetFeatured(v)
	return _c
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableFeatured(v *bool) *ProjectCreate {
	if v != nil {
		_c.SetFeatured(*v)
	}
	return _c
}

// SetPublished sets the "published" field.
func (_c *ProjectCreate) SetPublished(v bool) *ProjectCreate {
	_c.mutation.SetPublished(v)
	return _c
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_c *ProjectCreate) SetNillablePublished(v *bool) *ProjectCreate {
	if v != nil {
		_c.SetPublished(*v)
	}
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *ProjectCreate) SetDisplayOrder(v int) *ProjectCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableDisplayOrder(v *int) *ProjectCreate {
	if v != nil {
		_c.SetDisplayOrder(*v)
	}
	return _c
}

// SetRepositoryURL sets the "repository_url" field.
func (_c *ProjectCreate) SetRepositoryURL(v string) *ProjectCreate {
	_c.mutation.SetRepositoryURL(v)
	return _c
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableRepositoryURL(v *string) *ProjectCreate {
	if v != nil {
		_c.SetRepositoryURL(*v)
	}
	return _c
}

// SetLiveURL sets the "live_url" field.
func (_c *ProjectCreate) SetLiveURL(v string) *ProjectCreate {
	_c.mutation.SetLiveURL(v)
	return _c
}

// SetNillableLiveURL sets the "live_url" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableLiveURL(v *string) *ProjectCreate {
	if v != nil {
		_c.SetLiveURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectCreate) SetCreatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectCreate) SetUpdatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableUpdatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectCreate) SetID(v uuid.UUID) *ProjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableID(v *uuid.UUID) *ProjectCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTechnologyIDs adds the "technologies" edge to the Technology entity by IDs.
func (_c *ProjectCreate) AddTechnologyIDs(ids ...uuid.UUID) *ProjectCreate {
	_c.mutation.AddTechnologyIDs(ids...)
	return _c
}

// AddTechnologies adds the "technologies" edges to the Technology entity.
func (_c *ProjectCreate) AddTechnologies(v ...*Technology) *ProjectCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTechnologyIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() {
	if _, ok := _c.mutation.Featured(); !ok {
		v := project.DefaultFeatured
		_c.mutation.SetFeatured(v)
	}
	if _, ok := _c.mutation.Published(); !ok {
		v := project.DefaultPublished
		_c.mutation.SetPublished(v)
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		v := project.DefaultDisplayOrder
		_c.mutation.SetDisplayOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := project.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := project.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := project.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Project.slug"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Project.title"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Project.summary"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Project.period"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Project.role"`)}
	}
	if _, ok := _c.mutation.ContentMarkdown(); !ok {
		return &ValidationError{Name: "content_markdown", err: errors.New(`ent: missing required field "Project.content_markdown"`)}
	}
	if _, ok := _c.mutation.Featured(); !ok {
		return &ValidationError{Name: "featured", err: errors.New(`ent: missing required field "Project.featured"`)}
	}
	if _, ok := _c.mutation.Published(); !ok {
		return &ValidationError{Name: "published", err: errors.New(`ent: missing required field "Project.published"`)}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "Project.display_order"`)}
	}
	if v, ok := _c.mutation.DisplayOrder(); ok {
		if err := project.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "Project.display_order": %w`, err)}
		}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(project.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.ContentMarkdown(); ok {
		_spec.SetField(project.FieldContentMarkdown, field.TypeString, value)
		_node.ContentMarkdown = value
	}
	if value, ok := _c.mutation.Featured(); ok {
		_spec.SetField(project.FieldFeatured, field.TypeBool, value)
		_node.Featured = value
	}
	if value, ok := _c.mutation.Published(); ok {
		_spec.SetField(project.FieldPublished, field.TypeBool, value)
		_node.Published = value
	}
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if value, ok := _c.mutation.RepositoryURL(); ok {
		_spec.SetField(project.FieldRepositoryURL, field.TypeString, value)
		_node.RepositoryURL = &value
	}
	if value, ok := _c.mutation.LiveURL(); ok {
		_spec.SetField(project.FieldLiveURL, field.TypeString, value)
		_node.LiveURL = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _c.config, mutation: newProjectTechnologyMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Project.Create().
//		SetSlug(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectCreate) OnConflict(opts ...sql.ConflictOption) *ProjectUpsertOne {
	_c.conflict = opts
	return &ProjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectCreate) OnConflictColumns(columns ...string) *ProjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectUpsertOne{
		create: _c,
	}
}

type (
	// ProjectUpsertOne is the builder for "upsert"-ing
	//  one Project node.
	ProjectUpsertOne struct {
		create *ProjectCreate
	}

	// ProjectUpsert is the "OnConflict" setter.
	ProjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlug sets the "slug" field.
func (u *ProjectUpsert) SetSlug(v string) *ProjectUpsert {
	u.Set(project.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateSlug() *ProjectUpsert {
	u.SetExcluded(project.FieldSlug)
	return u
}

// SetTitle sets the "title" field.
func (u *ProjectUpsert) SetTitle(v string) *ProjectUpsert {
	u.Set(project.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateTitle() *ProjectUpsert {
	u.SetExcluded(project.FieldTitle)
	return u
}

// SetSummary sets the "summary" field.
func (u *ProjectUpsert) SetSummary(v string) *ProjectUpsert {
	u.Set(project.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateSummary() *ProjectUpsert {
	u.SetExcluded(project.FieldSummary)
	return u
}

// SetPeriod sets the "period" field.
func (u *ProjectUpsert) SetPeriod(v string) *ProjectUpsert {
	u.Set(project.FieldPeriod, v)
	return u
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ProjectUpsert) UpdatePeriod() *ProjectUpsert {
	u.SetExcluded(project.FieldPeriod)
	return u
}

// SetRole sets the "role" field.
func (u *ProjectUpsert) SetRole(v string) *ProjectUpsert {
	u.Set(project.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateRole() *ProjectUpsert {
	u.SetExcluded(project.FieldRole)
	return u
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *ProjectUpsert) SetContentMarkdown(v string) *ProjectUpsert {
	u.Set(project.FieldContentMarkdown, v)
	return u
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateContentMarkdown() *ProjectUpsert {
	u.SetExcluded(project.FieldContentMarkdown)
	return u
}

// SetFeatured sets the "featured" field.
func (u *ProjectUpsert) SetFeatured(v bool) *ProjectUpsert {
	u.Set(project.FieldFeatured, v)
	return u
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateFeatured() *ProjectUpsert {
	u.SetExcluded(project.FieldFeatured)
	return u
}

// SetPublished sets the "published" field.
func (u *ProjectUpsert) SetPublished(v bool) *ProjectUpsert {
	u.Set(project.FieldPublished, v)
	return u
}

// UpdatePublished sets the "published" field to the value that was provided on create.
func (u *ProjectUpsert) UpdatePublished() *ProjectUpsert {
	u.SetExcluded(project.FieldPublished)
	return u
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectUpsert) SetDisplayOrder(v int) *ProjectUpsert {
	u.Set(project.FieldDisplayOrder, v)
	return u
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateDisplayOrder() *ProjectUpsert {
	u.SetExcluded(project.FieldDisplayOrder)
	return u
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectUpsert) AddDisplayOrder(v int) *ProjectUpsert {
	u.Add(project.FieldDisplayOrder, v)
	return u
}

// SetRepositoryURL sets the "repository_url" field.
func (u *ProjectUpsert) SetRepositoryURL(v string) *ProjectUpsert {
	u.Set(project.FieldRepositoryURL, v)
	return u
}

// UpdateRepositoryURL sets the "repository_url" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateRepositoryURL() *ProjectUpsert {
	u.SetExcluded(project.FieldRepositoryURL)
	return u
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (u *ProjectUpsert) ClearRepositoryURL() *ProjectUpsert {
	u.SetNull(project.FieldRepositoryURL)
	return u
}

// SetLiveURL sets the "live_url" field.
func (u *ProjectUpsert) SetLiveURL(v string) *ProjectUpsert {
	u.Set(project.FieldLiveURL, v)
	return u
}

// UpdateLiveURL sets the "live_url" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateLiveURL() *ProjectUpsert {
	u.SetExcluded(project.FieldLiveURL)
	return u
}

// ClearLiveURL clears the value of the "live_url" field.
func (u *ProjectUpsert) ClearLiveURL() *ProjectUpsert {
	u.SetNull(project.FieldLiveURL)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsert) SetUpdatedAt(v time.Time) *ProjectUpsert {
	u.Set(project.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsert) UpdateUpdatedAt() *ProjectUpsert {
	u.SetExcluded(project.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(project.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProjectUpsertOne) UpdateNewValues() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(project.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(project.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProjectUpsertOne) Ignore() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectUpsertOne) DoNothing() *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectCreate.OnConflict
// documentation for more info.
func (u *ProjectUpsertOne) Update(set func(*ProjectUpsert)) *ProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *ProjectUpsertOne) SetSlug(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateSlug() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *ProjectUpsertOne) SetTitle(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateTitle() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateTitle()
	})
}

// SetSummary sets the "summary" field.
func (u *ProjectUpsertOne) SetSummary(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateSummary() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateSummary()
	})
}

// SetPeriod sets the "period" field.
func (u *ProjectUpsertOne) SetPeriod(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdatePeriod() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePeriod()
	})
}

// SetRole sets the "role" field.
func (u *ProjectUpsertOne) SetRole(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateRole() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRole()
	})
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *ProjectUpsertOne) SetContentMarkdown(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetContentMarkdown(v)
	})
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateContentMarkdown() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateContentMarkdown()
	})
}

// SetFeatured sets the "featured" field.
func (u *ProjectUpsertOne) SetFeatured(v bool) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateFeatured() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateFeatured()
	})
}

// SetPublished sets the "published" field.
func (u *ProjectUpsertOne) SetPublished(v bool) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPublished(v)
	})
}

// UpdatePublished sets the "published" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdatePublished() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePublished()
	})
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectUpsertOne) SetDisplayOrder(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectUpsertOne) AddDisplayOrder(v int) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateDisplayOrder() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDisplayOrder()
	})
}

// SetRepositoryURL sets the "repository_url" field.
func (u *ProjectUpsertOne) SetRepositoryURL(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRepositoryURL(v)
	})
}

// UpdateRepositoryURL sets the "repository_url" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateRepositoryURL() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRepositoryURL()
	})
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (u *ProjectUpsertOne) ClearRepositoryURL() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearRepositoryURL()
	})
}

// SetLiveURL sets the "live_url" field.
func (u *ProjectUpsertOne) SetLiveURL(v string) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetLiveURL(v)
	})
}

// UpdateLiveURL sets the "live_url" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateLiveURL() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateLiveURL()
	})
}

// ClearLiveURL clears the value of the "live_url" field.
func (u *ProjectUpsertOne) ClearLiveURL() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearLiveURL()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsertOne) SetUpdatedAt(v time.Time) *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsertOne) UpdateUpdatedAt() *ProjectUpsertOne {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProjectUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProjectUpsertOne.ID is not supported by MySQL driver. Use ProjectUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProjectUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
	conflict []sql.ConflictOption
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Project.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProjectUpsertBulk {
	_c.conflict = opts
	return &ProjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectCreateBulk) OnConflictColumns(columns ...string) *ProjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectUpsertBulk{
		create: _c,
	}
}

// ProjectUpsertBulk is the builder for "upsert"-ing
// a bulk of Project nodes.
type ProjectUpsertBulk struct {
	create *ProjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(project.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProjectUpsertBulk) UpdateNewValues() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(project.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(project.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Project.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProjectUpsertBulk) Ignore() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectUpsertBulk) DoNothing() *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectCreateBulk.OnConflict
// documentation for more info.
func (u *ProjectUpsertBulk) Update(set func(*ProjectUpsert)) *ProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *ProjectUpsertBulk) SetSlug(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateSlug() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *ProjectUpsertBulk) SetTitle(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateTitle() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateTitle()
	})
}

// SetSummary sets the "summary" field.
func (u *ProjectUpsertBulk) SetSummary(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateSummary() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateSummary()
	})
}

// SetPeriod sets the "period" field.
func (u *ProjectUpsertBulk) SetPeriod(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPeriod(v)
	})
}

// UpdatePeriod sets the "period" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdatePeriod() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePeriod()
	})
}

// SetRole sets the "role" field.
func (u *ProjectUpsertBulk) SetRole(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateRole() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRole()
	})
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *ProjectUpsertBulk) SetContentMarkdown(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetContentMarkdown(v)
	})
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateContentMarkdown() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateContentMarkdown()
	})
}

// SetFeatured sets the "featured" field.
func (u *ProjectUpsertBulk) SetFeatured(v bool) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetFeatured(v)
	})
}

// UpdateFeatured sets the "featured" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateFeatured() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateFeatured()
	})
}

// SetPublished sets the "published" field.
func (u *ProjectUpsertBulk) SetPublished(v bool) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetPublished(v)
	})
}

// UpdatePublished sets the "published" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdatePublished() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdatePublished()
	})
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectUpsertBulk) SetDisplayOrder(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectUpsertBulk) AddDisplayOrder(v int) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateDisplayOrder() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateDisplayOrder()
	})
}

// SetRepositoryURL sets the "repository_url" field.
func (u *ProjectUpsertBulk) SetRepositoryURL(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetRepositoryURL(v)
	})
}

// UpdateRepositoryURL sets the "repository_url" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateRepositoryURL() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateRepositoryURL()
	})
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (u *ProjectUpsertBulk) ClearRepositoryURL() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearRepositoryURL()
	})
}

// SetLiveURL sets the "live_url" field.
func (u *ProjectUpsertBulk) SetLiveURL(v string) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetLiveURL(v)
	})
}

// UpdateLiveURL sets the "live_url" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateLiveURL() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateLiveURL()
	})
}

// ClearLiveURL clears the value of the "live_url" field.
func (u *ProjectUpsertBulk) ClearLiveURL() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.ClearLiveURL()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProjectUpsertBulk) SetUpdatedAt(v time.Time) *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProjectUpsertBulk) UpdateUpdatedAt() *ProjectUpsertBulk {
	return u.Update(func(s *ProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
