// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// ProjectTechnology is the model entity for the ProjectTechnology schema.
type ProjectTechnology struct {
	config `json:"-"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// TechnologyID holds the value of the "technology_id" field.
	TechnologyID uuid.UUID `json:"technology_id,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectTechnologyQuery when eager-loading is set.
	Edges        ProjectTechnologyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectTechnologyEdges holds the relations/edges for other nodes in the graph.
type ProjectTechnologyEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Technology holds the value of the technology edge.
	Technology *Technology `json:"technology,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectTechnologyEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TechnologyOrErr returns the Technology value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectTechnologyEdges) TechnologyOrErr() (*Technology, error) {
	if e.Technology != nil {
		return e.Technology, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: technology.Label}
	}
	return nil, &NotLoadedError{edge: "technology"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectTechnology) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projecttechnology.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case projecttechnology.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case projecttechnology.FieldProjectID, projecttechnology.FieldTechnologyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectTechnology fields.
func (_m *ProjectTechnology) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projecttechnology.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projecttechnology.FieldTechnologyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field technology_id", values[i])
			} else if value != nil {
				_m.TechnologyID = *value
			}
		case projecttechnology.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case projecttechnology.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectTechnology.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectTechnology) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectTechnology entity.
func (_m *ProjectTechnology) QueryProject() *ProjectQuery {
	return NewProjectTechnologyClient(_m.config).QueryProject(_m)
}

// QueryTechnology queries the "technology" edge of the ProjectTechnology entity.
func (_m *ProjectTechnology) QueryTechnology() *TechnologyQuery {
	return NewProjectTechnologyClient(_m.config).QueryTechnology(_m)
}

// Update returns a builder for updating this ProjectTechnology.
// Note that you need to call ProjectTechnology.Unwrap() before calling this method if this ProjectTechnology
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectTechnology) Update() *ProjectTechnologyUpdateOne {
	return NewProjectTechnologyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectTechnology entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectTechnology) Unwrap() *ProjectTechnology {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectTechnology is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectTechnology) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectTechnology(")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("technology_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TechnologyID))
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectTechnologies is a parsable slice of ProjectTechnology.
type ProjectTechnologies []*ProjectTechnology
