// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Period holds the value of the "period" field.
	Period string `json:"period,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// ContentMarkdown holds the value of the "content_markdown" field.
	ContentMarkdown string `json:"content_markdown,omitempty"`
	// Featured holds the value of the "featured" field.
	Featured bool `json:"featured,omitempty"`
	// Published holds the value of the "published" field.
	Published bool `json:"published,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// RepositoryURL holds the value of the "repository_url" field.
	RepositoryURL *string `json:"repository_url,omitempty"`
	// LiveURL holds the value of the "live_url" field.
	LiveURL *string `json:"live_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Technologies holds the value of the technologies edge.
	Technologies []*Technology `json:"technologies,omitempty"`
	// TechnologyLinks holds the value of the technology_links edge.
	TechnologyLinks []*ProjectTechnology `json:"technology_links,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TechnologiesOrErr returns the Technologies value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) TechnologiesOrErr() ([]*Technology, error) {
	if e.loadedTypes[0] {
		return e.Technologies, nil
	}
	return nil, &NotLoadedError{edge: "technologies"}
}

// TechnologyLinksOrErr returns the TechnologyLinks value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) TechnologyLinksOrErr() ([]*ProjectTechnology, error) {
	if e.loadedTypes[1] {
		return e.TechnologyLinks, nil
	}
	return nil, &NotLoadedError{edge: "technology_links"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldFeatured, project.FieldPublished:
			values[i] = new(sql.NullBool)
		case project.FieldDisplayOrder:
			values[i] = new(sql.NullInt64)
		case project.FieldSlug, project.FieldTitle, project.FieldSummary, project.FieldPeriod, project.FieldRole, project.FieldContentMarkdown, project.FieldRepositoryURL, project.FieldLiveURL:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case project.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case project.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case project.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case project.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case project.FieldPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field period", values[i])
			} else if value.Valid {
				_m.Period = value.String
			}
		case project.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case project.FieldContentMarkdown:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_markdown", values[i])
			} else if value.Valid {
				_m.ContentMarkdown = value.String
			}
		case project.FieldFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field featured", values[i])
			} else if value.Valid {
				_m.Featured = value.Bool
			}
		case project.FieldPublished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field published", values[i])
			} else if value.Valid {
				_m.Published = value.Bool
			}
		case project.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case project.FieldRepositoryURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repository_url", values[i])
			} else if value.Valid {
				_m.RepositoryURL = new(string)
				*_m.RepositoryURL = value.String
			}
		case project.FieldLiveURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field live_url", values[i])
			} else if value.Valid {
				_m.LiveURL = new(string)
				*_m.LiveURL = value.String
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTechnologies queries the "technologies" edge of the Project entity.
func (_m *Project) QueryTechnologies() *TechnologyQuery {
	return NewProjectClient(_m.config).QueryTechnologies(_m)
}

// QueryTechnologyLinks queries the "technology_links" edge of the Project entity.
func (_m *Project) QueryTechnologyLinks() *ProjectTechnologyQuery {
	return NewProjectClient(_m.config).QueryTechnologyLinks(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("period=")
	builder.WriteString(_m.Period)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content_markdown=")
	builder.WriteString(_m.ContentMarkdown)
	builder.WriteString(", ")
	builder.WriteString("featured=")
	builder.WriteString(fmt.Sprintf("%v", _m.Featured))
	builder.WriteString(", ")
	builder.WriteString("published=")
	builder.WriteString(fmt.Sprintf("%v", _m.Published))
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteString(", ")
	if v := _m.RepositoryURL; v != nil {
		builder.WriteString("repository_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LiveURL; v != nil {
		builder.WriteString("live_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
