// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/predicate"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ProjectUpdate) SetSlug(v string) *ProjectUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableSlug(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdate) SetTitle(v string) *ProjectUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableTitle(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdate) SetSummary(v string) *ProjectUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableSummary(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *ProjectUpdate) SetPeriod(v string) *ProjectUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePeriod(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectUpdate) SetRole(v string) *ProjectUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRole(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContentMarkdown sets the "content_markdown" field.
func (_u *ProjectUpdate) SetContentMarkdown(v string) *ProjectUpdate {
	_u.mutation.SetContentMarkdown(v)
	return _u
}

// SetNillableContentMarkdown sets the "content_markdown" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableContentMarkdown(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetContentMarkdown(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ProjectUpdate) SetFeatured(v bool) *ProjectUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableFeatured(v *bool) *ProjectUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *ProjectUpdate) SetPublished(v bool) *ProjectUpdate {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePublished(v *bool) *ProjectUpdate {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectUpdate) SetDisplayOrder(v int) *ProjectUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDisplayOrder(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectUpdate) AddDisplayOrder(v int) *ProjectUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetRepositoryURL sets the "repository_url" field.
func (_u *ProjectUpdate) SetRepositoryURL(v string) *ProjectUpdate {
	_u.mutation.SetRepositoryURL(v)
	return _u
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRepositoryURL(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRepositoryURL(*v)
	}
	return _u
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (_u *ProjectUpdate) ClearRepositoryURL() *ProjectUpdate {
	_u.mutation.ClearRepositoryURL()
	return _u
}

// SetLiveURL sets the "live_url" field.
func (_u *ProjectUpdate) SetLiveURL(v string) *ProjectUpdate {
	_u.mutation.SetLiveURL(v)
	return _u
}

// SetNillableLiveURL sets the "live_url" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableLiveURL(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetLiveURL(*v)
	}
	return _u
}

// ClearLiveURL clears the value of the "live_url" field.
func (_u *ProjectUpdate) ClearLiveURL() *ProjectUpdate {
	_u.mutation.ClearLiveURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTechnologyIDs adds the "technologies" edge to the Technology entity by IDs.
func (_u *ProjectUpdate) AddTechnologyIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddTechnologyIDs(ids...)
	return _u
}

// AddTechnologies adds the "technologies" edges to the Technology entity.
func (_u *ProjectUpdate) AddTechnologies(v ...*Technology) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechnologyIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTechnologies clears all "technologies" edges to the Technology entity.
func (_u *ProjectUpdate) ClearTechnologies() *ProjectUpdate {
	_u.mutation.ClearTechnologies()
	return _u
}

// RemoveTechnologyIDs removes the "technologies" edge to Technology entities by IDs.
func (_u *ProjectUpdate) RemoveTechnologyIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveTechnologyIDs(ids...)
	return _u
}

// RemoveTechnologies removes "technologies" edges to Technology entities.
func (_u *ProjectUpdate) RemoveTechnologies(v ...*Technology) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechnologyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := project.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "Project.display_order": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(project.FieldPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMarkdown(); ok {
		_spec.SetField(project.FieldContentMarkdown, field.TypeString, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(project.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(project.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RepositoryURL(); ok {
		_spec.SetField(project.FieldRepositoryURL, field.TypeString, value)
	}
	if _u.mutation.RepositoryURLCleared() {
		_spec.ClearField(project.FieldRepositoryURL, field.TypeString)
	}
	if value, ok := _u.mutation.LiveURL(); ok {
		_spec.SetField(project.FieldLiveURL, field.TypeString, value)
	}
	if _u.mutation.LiveURLCleared() {
		_spec.ClearField(project.FieldLiveURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechnologiesIDs(); len(nodes) > 0 && !_u.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetSlug sets the "slug" field.
func (_u *ProjectUpdateOne) SetSlug(v string) *ProjectUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableSlug(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdateOne) SetTitle(v string) *ProjectUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableTitle(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdateOne) SetSummary(v string) *ProjectUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableSummary(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *ProjectUpdateOne) SetPeriod(v string) *ProjectUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePeriod(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectUpdateOne) SetRole(v string) *ProjectUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRole(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContentMarkdown sets the "content_markdown" field.
func (_u *ProjectUpdateOne) SetContentMarkdown(v string) *ProjectUpdateOne {
	_u.mutation.SetContentMarkdown(v)
	return _u
}

// SetNillableContentMarkdown sets the "content_markdown" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableContentMarkdown(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetContentMarkdown(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ProjectUpdateOne) SetFeatured(v bool) *ProjectUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableFeatured(v *bool) *ProjectUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetPublished sets the "published" field.
func (_u *ProjectUpdateOne) SetPublished(v bool) *ProjectUpdateOne {
	_u.mutation.SetPublished(v)
	return _u
}

// SetNillablePublished sets the "published" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePublished(v *bool) *ProjectUpdateOne {
	if v != nil {
		_u.SetPublished(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectUpdateOne) SetDisplayOrder(v int) *ProjectUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDisplayOrder(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectUpdateOne) AddDisplayOrder(v int) *ProjectUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetRepositoryURL sets the "repository_url" field.
func (_u *ProjectUpdateOne) SetRepositoryURL(v string) *ProjectUpdateOne {
	_u.mutation.SetRepositoryURL(v)
	return _u
}

// SetNillableRepositoryURL sets the "repository_url" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRepositoryURL(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRepositoryURL(*v)
	}
	return _u
}

// ClearRepositoryURL clears the value of the "repository_url" field.
func (_u *ProjectUpdateOne) ClearRepositoryURL() *ProjectUpdateOne {
	_u.mutation.ClearRepositoryURL()
	return _u
}

// SetLiveURL sets the "live_url" field.
func (_u *ProjectUpdateOne) SetLiveURL(v string) *ProjectUpdateOne {
	_u.mutation.SetLiveURL(v)
	return _u
}

// SetNillableLiveURL sets the "live_url" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableLiveURL(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetLiveURL(*v)
	}
	return _u
}

// ClearLiveURL clears the value of the "live_url" field.
func (_u *ProjectUpdateOne) ClearLiveURL() *ProjectUpdateOne {
	_u.mutation.ClearLiveURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTechnologyIDs adds the "technologies" edge to the Technology entity by IDs.
func (_u *ProjectUpdateOne) AddTechnologyIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddTechnologyIDs(ids...)
	return _u
}

// AddTechnologies adds the "technologies" edges to the Technology entity.
func (_u *ProjectUpdateOne) AddTechnologies(v ...*Technology) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechnologyIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTechnologies clears all "technologies" edges to the Technology entity.
func (_u *ProjectUpdateOne) ClearTechnologies() *ProjectUpdateOne {
	_u.mutation.ClearTechnologies()
	return _u
}

// RemoveTechnologyIDs removes the "technologies" edge to Technology entities by IDs.
func (_u *ProjectUpdateOne) RemoveTechnologyIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveTechnologyIDs(ids...)
	return _u
}

// RemoveTechnologies removes "technologies" edges to Technology entities.
func (_u *ProjectUpdateOne) RemoveTechnologies(v ...*Technology) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechnologyIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := project.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "Project.display_order": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(project.FieldPeriod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(project.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentMarkdown(); ok {
		_spec.SetField(project.FieldContentMarkdown, field.TypeString, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(project.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Published(); ok {
		_spec.SetField(project.FieldPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(project.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RepositoryURL(); ok {
		_spec.SetField(project.FieldRepositoryURL, field.TypeString, value)
	}
	if _u.mutation.RepositoryURLCleared() {
		_spec.ClearField(project.FieldRepositoryURL, field.TypeString)
	}
	if value, ok := _u.mutation.LiveURL(); ok {
		_spec.SetField(project.FieldLiveURL, field.TypeString, value)
	}
	if _u.mutation.LiveURLCleared() {
		_spec.ClearField(project.FieldLiveURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechnologiesIDs(); len(nodes) > 0 && !_u.mutation.TechnologiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechnologiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TechnologiesTable,
			Columns: project.TechnologiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _u.config, mutation: newProjectTechnologyMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
