// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// ProjectTechnologyCreate is the builder for creating a ProjectTechnology entity.
type ProjectTechnologyCreate struct {
	config
	mutation *ProjectTechnologyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectID sets the "project_id" field.
func (_c *ProjectTechnologyCreate) SetProjectID(v uuid.UUID) *ProjectTechnologyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTechnologyID sets the "technology_id" field.
func (_c *ProjectTechnologyCreate) SetTechnologyID(v uuid.UUID) *ProjectTechnologyCreate {
	_c.mutation.SetTechnologyID(v)
	return _c
}

// SetDisplayOrder sets the "display_order" field.
func (_c *ProjectTechnologyCreate) SetDisplayOrder(v int) *ProjectTechnologyCreate {
	_c.mutation.SetDisplayOrder(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectTechnologyCreate) SetCreatedAt(v time.Time) *ProjectTechnologyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectTechnologyCreate) SetNillableCreatedAt(v *time.Time) *ProjectTechnologyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectTechnologyCreate) SetProject(v *Project) *ProjectTechnologyCreate {
	return _c.SetProjectID(v.ID)
}

// SetTechnology sets the "technology" edge to the Technology entity.
func (_c *ProjectTechnologyCreate) SetTechnology(v *Technology) *ProjectTechnologyCreate {
	return _c.SetTechnologyID(v.ID)
}

// Mutation returns the ProjectTechnologyMutation object of the builder.
func (_c *ProjectTechnologyCreate) Mutation() *ProjectTechnologyMutation {
	return _c.mutation
}

// Save creates the ProjectTechnology in the database.
func (_c *ProjectTechnologyCreate) Save(ctx context.Context) (*ProjectTechnology, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectTechnologyCreate) SaveX(ctx context.Context) *ProjectTechnology {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTechnologyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTechnologyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectTechnologyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projecttechnology.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectTechnologyCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ProjectTechnology.project_id"`)}
	}
	if _, ok := _c.mutation.TechnologyID(); !ok {
		return &ValidationError{Name: "technology_id", err: errors.New(`ent: missing required field "ProjectTechnology.technology_id"`)}
	}
	if _, ok := _c.mutation.DisplayOrder(); !ok {
		return &ValidationError{Name: "display_order", err: errors.New(`ent: missing required field "ProjectTechnology.display_order"`)}
	}
	if v, ok := _c.mutation.DisplayOrder(); ok {
		if err := projecttechnology.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "ProjectTechnology.display_order": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectTechnology.project"`)}
	}
	if len(_c.mutation.TechnologyIDs()) == 0 {
		return &ValidationError{Name: "technology", err: errors.New(`ent: missing required edge "ProjectTechnology.technology"`)}
	}
	return nil
}

func (_c *ProjectTechnologyCreate) sqlSave(ctx context.Context) (*ProjectTechnology, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ProjectTechnologyCreate) createSpec() (*ProjectTechnology, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectTechnology{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projecttechnology.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DisplayOrder(); ok {
		_spec.SetField(projecttechnology.FieldDisplayOrder, field.TypeInt, value)
		_node.DisplayOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projecttechnology.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttechnology.ProjectTable,
			Columns: []string{projecttechnology.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TechnologyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projecttechnology.TechnologyTable,
			Columns: []string{projecttechnology.TechnologyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TechnologyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectTechnology.Create().
//		SetProjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectTechnologyUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectTechnologyCreate) OnConflict(opts ...sql.ConflictOption) *ProjectTechnologyUpsertOne {
	_c.conflict = opts
	return &ProjectTechnologyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectTechnologyCreate) OnConflictColumns(columns ...string) *ProjectTechnologyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectTechnologyUpsertOne{
		create: _c,
	}
}

type (
	// ProjectTechnologyUpsertOne is the builder for "upsert"-ing
	//  one ProjectTechnology node.
	ProjectTechnologyUpsertOne struct {
		create *ProjectTechnologyCreate
	}

	// ProjectTechnologyUpsert is the "OnConflict" setter.
	ProjectTechnologyUpsert struct {
		*sql.UpdateSet
	}
)

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectTechnologyUpsert) SetDisplayOrder(v int) *ProjectTechnologyUpsert {
	u.Set(projecttechnology.FieldDisplayOrder, v)
	return u
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectTechnologyUpsert) UpdateDisplayOrder() *ProjectTechnologyUpsert {
	u.SetExcluded(projecttechnology.FieldDisplayOrder)
	return u
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectTechnologyUpsert) AddDisplayOrder(v int) *ProjectTechnologyUpsert {
	u.Add(projecttechnology.FieldDisplayOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectTechnologyUpsertOne) UpdateNewValues() *ProjectTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(projecttechnology.FieldProjectID)
		}
		if _, exists := u.create.mutation.TechnologyID(); exists {
			s.SetIgnore(projecttechnology.FieldTechnologyID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(projecttechnology.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProjectTechnologyUpsertOne) Ignore() *ProjectTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectTechnologyUpsertOne) DoNothing() *ProjectTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectTechnologyCreate.OnConflict
// documentation for more info.
func (u *ProjectTechnologyUpsertOne) Update(set func(*ProjectTechnologyUpsert)) *ProjectTechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectTechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectTechnologyUpsertOne) SetDisplayOrder(v int) *ProjectTechnologyUpsertOne {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectTechnologyUpsertOne) AddDisplayOrder(v int) *ProjectTechnologyUpsertOne {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectTechnologyUpsertOne) UpdateDisplayOrder() *ProjectTechnologyUpsertOne {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.UpdateDisplayOrder()
	})
}

// Exec executes the query.
func (u *ProjectTechnologyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectTechnologyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectTechnologyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// ProjectTechnologyCreateBulk is the builder for creating many ProjectTechnology entities in bulk.
type ProjectTechnologyCreateBulk struct {
	config
	err      error
	builders []*ProjectTechnologyCreate
	conflict []sql.ConflictOption
}

// Save creates the ProjectTechnology entities in the database.
func (_c *ProjectTechnologyCreateBulk) Save(ctx context.Context) ([]*ProjectTechnology, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectTechnology, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectTechnologyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectTechnologyCreateBulk) SaveX(ctx context.Context) []*ProjectTechnology {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectTechnologyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectTechnologyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProjectTechnology.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProjectTechnologyUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProjectTechnologyCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProjectTechnologyUpsertBulk {
	_c.conflict = opts
	return &ProjectTechnologyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProjectTechnologyCreateBulk) OnConflictColumns(columns ...string) *ProjectTechnologyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProjectTechnologyUpsertBulk{
		create: _c,
	}
}

// ProjectTechnologyUpsertBulk is the builder for "upsert"-ing
// a bulk of ProjectTechnology nodes.
type ProjectTechnologyUpsertBulk struct {
	create *ProjectTechnologyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProjectTechnologyUpsertBulk) UpdateNewValues() *ProjectTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(projecttechnology.FieldProjectID)
			}
			if _, exists := b.mutation.TechnologyID(); exists {
				s.SetIgnore(projecttechnology.FieldTechnologyID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(projecttechnology.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProjectTechnology.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProjectTechnologyUpsertBulk) Ignore() *ProjectTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProjectTechnologyUpsertBulk) DoNothing() *ProjectTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProjectTechnologyCreateBulk.OnConflict
// documentation for more info.
func (u *ProjectTechnologyUpsertBulk) Update(set func(*ProjectTechnologyUpsert)) *ProjectTechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProjectTechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayOrder sets the "display_order" field.
func (u *ProjectTechnologyUpsertBulk) SetDisplayOrder(v int) *ProjectTechnologyUpsertBulk {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.SetDisplayOrder(v)
	})
}

// AddDisplayOrder adds v to the "display_order" field.
func (u *ProjectTechnologyUpsertBulk) AddDisplayOrder(v int) *ProjectTechnologyUpsertBulk {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.AddDisplayOrder(v)
	})
}

// UpdateDisplayOrder sets the "display_order" field to the value that was provided on create.
func (u *ProjectTechnologyUpsertBulk) UpdateDisplayOrder() *ProjectTechnologyUpsertBulk {
	return u.Update(func(s *ProjectTechnologyUpsert) {
		s.UpdateDisplayOrder()
	})
}

// Exec executes the query.
func (u *ProjectTechnologyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProjectTechnologyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProjectTechnologyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProjectTechnologyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
