// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/predicate"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// ProjectTechnologyQuery is the builder for querying ProjectTechnology entities.
type ProjectTechnologyQuery struct {
	config
	ctx            *QueryContext
	order          []projecttechnology.OrderOption
	inters         []Interceptor
	predicates     []predicate.ProjectTechnology
	withProject    *ProjectQuery
	withTechnology *TechnologyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProjectTechnologyQuery builder.
func (_q *ProjectTechnologyQuery) Where(ps ...predicate.ProjectTechnology) *ProjectTechnologyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProjectTechnologyQuery) Limit(limit int) *ProjectTechnologyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProjectTechnologyQuery) Offset(offset int) *ProjectTechnologyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProjectTechnologyQuery) Unique(unique bool) *ProjectTechnologyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProjectTechnologyQuery) Order(o ...projecttechnology.OrderOption) *ProjectTechnologyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *ProjectTechnologyQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttechnology.Table, projecttechnology.ProjectColumn, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, projecttechnology.ProjectTable, projecttechnology.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTechnology chains the current query on the "technology" edge.
func (_q *ProjectTechnologyQuery) QueryTechnology() *TechnologyQuery {
	query := (&TechnologyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(projecttechnology.Table, projecttechnology.TechnologyColumn, selector),
			sqlgraph.To(technology.Table, technology.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, projecttechnology.TechnologyTable, projecttechnology.TechnologyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProjectTechnology entity from the query.
// Returns a *NotFoundError when no ProjectTechnology was found.
func (_q *ProjectTechnologyQuery) First(ctx context.Context) (*ProjectTechnology, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{projecttechnology.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProjectTechnologyQuery) FirstX(ctx context.Context) *ProjectTechnology {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single ProjectTechnology entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProjectTechnology entity is found.
// Returns a *NotFoundError when no ProjectTechnology entities are found.
func (_q *ProjectTechnologyQuery) Only(ctx context.Context) (*ProjectTechnology, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{projecttechnology.Label}
	default:
		return nil, &NotSingularError{projecttechnology.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProjectTechnologyQuery) OnlyX(ctx context.Context) *ProjectTechnology {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of ProjectTechnologies.
func (_q *ProjectTechnologyQuery) All(ctx context.Context) ([]*ProjectTechnology, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProjectTechnology, *ProjectTechnologyQuery]()
	return withInterceptors[[]*ProjectTechnology](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProjectTechnologyQuery) AllX(ctx context.Context) []*ProjectTechnology {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *ProjectTechnologyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProjectTechnologyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProjectTechnologyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProjectTechnologyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProjectTechnologyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProjectTechnologyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProjectTechnologyQuery) Clone() *ProjectTechnologyQuery {
	if _q == nil {
		return nil
	}
	return &ProjectTechnologyQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]projecttechnology.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.ProjectTechnology{}, _q.predicates...),
		withProject:    _q.withProject.Clone(),
		withTechnology: _q.withTechnology.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTechnologyQuery) WithProject(opts ...func(*ProjectQuery)) *ProjectTechnologyQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithTechnology tells the query-builder to eager-load the nodes that are connected to
// the "technology" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProjectTechnologyQuery) WithTechnology(opts ...func(*TechnologyQuery)) *ProjectTechnologyQuery {
	query := (&TechnologyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTechnology = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProjectTechnology.Query().
//		GroupBy(projecttechnology.FieldProjectID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProjectTechnologyQuery) GroupBy(field string, fields ...string) *ProjectTechnologyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProjectTechnologyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = projecttechnology.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//	}
//
//	client.ProjectTechnology.Query().
//		Select(projecttechnology.FieldProjectID).
//		Scan(ctx, &v)
func (_q *ProjectTechnologyQuery) Select(fields ...string) *ProjectTechnologySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProjectTechnologySelect{ProjectTechnologyQuery: _q}
	sbuild.label = projecttechnology.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProjectTechnologySelect configured with the given aggregations.
func (_q *ProjectTechnologyQuery) Aggregate(fns ...AggregateFunc) *ProjectTechnologySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProjectTechnologyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !projecttechnology.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProjectTechnologyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProjectTechnology, error) {
	var (
		nodes       = []*ProjectTechnology{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProject != nil,
			_q.withTechnology != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProjectTechnology).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProjectTechnology{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *ProjectTechnology, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTechnology; query != nil {
		if err := _q.loadTechnology(ctx, query, nodes, nil,
			func(n *ProjectTechnology, e *Technology) { n.Edges.Technology = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProjectTechnologyQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*ProjectTechnology, init func(*ProjectTechnology), assign func(*ProjectTechnology, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTechnology)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProjectTechnologyQuery) loadTechnology(ctx context.Context, query *TechnologyQuery, nodes []*ProjectTechnology, init func(*ProjectTechnology), assign func(*ProjectTechnology, *Technology)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProjectTechnology)
	for i := range nodes {
		fk := nodes[i].TechnologyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(technology.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "technology_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProjectTechnologyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProjectTechnologyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(projecttechnology.Table, projecttechnology.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(projecttechnology.FieldProjectID)
		}
		if _q.withTechnology != nil {
			_spec.Node.AddColumnOnce(projecttechnology.FieldTechnologyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProjectTechnologyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(projecttechnology.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = projecttechnology.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProjectTechnologyGroupBy is the group-by builder for ProjectTechnology entities.
type ProjectTechnologyGroupBy struct {
	selector
	build *ProjectTechnologyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProjectTechnologyGroupBy) Aggregate(fns ...AggregateFunc) *ProjectTechnologyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProjectTechnologyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectTechnologyQuery, *ProjectTechnologyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProjectTechnologyGroupBy) sqlScan(ctx context.Context, root *ProjectTechnologyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProjectTechnologySelect is the builder for selecting fields of ProjectTechnology entities.
type ProjectTechnologySelect struct {
	*ProjectTechnologyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProjectTechnologySelect) Aggregate(fns ...AggregateFunc) *ProjectTechnologySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProjectTechnologySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProjectTechnologyQuery, *ProjectTechnologySelect](ctx, _s.ProjectTechnologyQuery, _s, _s.inters, v)
}

func (_s *ProjectTechnologySelect) sqlScan(ctx context.Context, root *ProjectTechnologyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
