// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/predicate"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
)

// ProjectTechnologyUpdate is the builder for updating ProjectTechnology entities.
type ProjectTechnologyUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectTechnologyMutation
}

// Where appends a list predicates to the ProjectTechnologyUpdate builder.
func (_u *ProjectTechnologyUpdate) Where(ps ...predicate.ProjectTechnology) *ProjectTechnologyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectTechnologyUpdate) SetDisplayOrder(v int) *ProjectTechnologyUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectTechnologyUpdate) SetNillableDisplayOrder(v *int) *ProjectTechnologyUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectTechnologyUpdate) AddDisplayOrder(v int) *ProjectTechnologyUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the ProjectTechnologyMutation object of the builder.
func (_u *ProjectTechnologyUpdate) Mutation() *ProjectTechnologyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectTechnologyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTechnologyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectTechnologyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTechnologyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTechnologyUpdate) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := projecttechnology.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "ProjectTechnology.display_order": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTechnology.project"`)
	}
	if _u.mutation.TechnologyCleared() && len(_u.mutation.TechnologyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTechnology.technology"`)
	}
	return nil
}

func (_u *ProjectTechnologyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttechnology.Table, projecttechnology.Columns, sqlgraph.NewFieldSpec(projecttechnology.FieldProjectID, field.TypeUUID), sqlgraph.NewFieldSpec(projecttechnology.FieldTechnologyID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(projecttechnology.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(projecttechnology.FieldDisplayOrder, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttechnology.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectTechnologyUpdateOne is the builder for updating a single ProjectTechnology entity.
type ProjectTechnologyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectTechnologyMutation
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ProjectTechnologyUpdateOne) SetDisplayOrder(v int) *ProjectTechnologyUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ProjectTechnologyUpdateOne) SetNillableDisplayOrder(v *int) *ProjectTechnologyUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ProjectTechnologyUpdateOne) AddDisplayOrder(v int) *ProjectTechnologyUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// Mutation returns the ProjectTechnologyMutation object of the builder.
func (_u *ProjectTechnologyUpdateOne) Mutation() *ProjectTechnologyMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProjectTechnologyUpdate builder.
func (_u *ProjectTechnologyUpdateOne) Where(ps ...predicate.ProjectTechnology) *ProjectTechnologyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectTechnologyUpdateOne) Select(field string, fields ...string) *ProjectTechnologyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectTechnology entity.
func (_u *ProjectTechnologyUpdateOne) Save(ctx context.Context) (*ProjectTechnology, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTechnologyUpdateOne) SaveX(ctx context.Context) *ProjectTechnology {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectTechnologyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTechnologyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTechnologyUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := projecttechnology.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "ProjectTechnology.display_order": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTechnology.project"`)
	}
	if _u.mutation.TechnologyCleared() && len(_u.mutation.TechnologyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTechnology.technology"`)
	}
	return nil
}

func (_u *ProjectTechnologyUpdateOne) sqlSave(ctx context.Context) (_node *ProjectTechnology, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttechnology.Table, projecttechnology.Columns, sqlgraph.NewFieldSpec(projecttechnology.FieldProjectID, field.TypeUUID), sqlgraph.NewFieldSpec(projecttechnology.FieldTechnologyID, field.TypeUUID))
	if id, ok := _u.mutation.ProjectID(); !ok {
		return nil, &ValidationError{Name: "project_id", err: errors.New(`ent: missing "ProjectTechnology.project_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.TechnologyID(); !ok {
		return nil, &ValidationError{Name: "technology_id", err: errors.New(`ent: missing "ProjectTechnology.technology_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !projecttechnology.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(projecttechnology.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(projecttechnology.FieldDisplayOrder, field.TypeInt, value)
	}
	_node = &ProjectTechnology{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttechnology.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
