// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/projecttechnology"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/schema"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescFeatured is the schema descriptor for featured field.
	projectDescFeatured := projectFields[7].Descriptor()
	// project.DefaultFeatured holds the default value on creation for the featured field.
	project.DefaultFeatured = projectDescFeatured.Default.(bool)
	// projectDescPublished is the schema descriptor for published field.
	projectDescPublished := projectFields[8].Descriptor()
	// project.DefaultPublished holds the default value on creation for the published field.
	project.DefaultPublished = projectDescPublished.Default.(bool)
	// projectDescDisplayOrder is the schema descriptor for display_order field.
	projectDescDisplayOrder := projectFields[9].Descriptor()
	// project.DefaultDisplayOrder holds the default value on creation for the display_order field.
	project.DefaultDisplayOrder = projectDescDisplayOrder.Default.(int)
	// project.DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	project.DisplayOrderValidator = projectDescDisplayOrder.Validators[0].(func(int) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[12].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[13].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	projecttechnologyFields := schema.ProjectTechnology{}.Fields()
	_ = projecttechnologyFields
	// projecttechnologyDescDisplayOrder is the schema descriptor for display_order field.
	projecttechnologyDescDisplayOrder := projecttechnologyFields[2].Descriptor()
	// projecttechnology.DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	projecttechnology.DisplayOrderValidator = projecttechnologyDescDisplayOrder.Validators[0].(func(int) error)
	// projecttechnologyDescCreatedAt is the schema descriptor for created_at field.
	projecttechnologyDescCreatedAt := projecttechnologyFields[3].Descriptor()
	// projecttechnology.DefaultCreatedAt holds the default value on creation for the created_at field.
	projecttechnology.DefaultCreatedAt = projecttechnologyDescCreatedAt.Default.(func() time.Time)
	technologyFields := schema.Technology{}.Fields()
	_ = technologyFields
	// technologyDescCreatedAt is the schema descriptor for created_at field.
	technologyDescCreatedAt := technologyFields[4].Descriptor()
	// technology.DefaultCreatedAt holds the default value on creation for the created_at field.
	technology.DefaultCreatedAt = technologyDescCreatedAt.Default.(func() time.Time)
	// technologyDescUpdatedAt is the schema descriptor for updated_at field.
	technologyDescUpdatedAt := technologyFields[5].Descriptor()
	// technology.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	technology.DefaultUpdatedAt = technologyDescUpdatedAt.Default.(func() time.Time)
	// technology.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	technology.UpdateDefaultUpdatedAt = technologyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// technologyDescID is the schema descriptor for id field.
	technologyDescID := technologyFields[0].Descriptor()
	// technology.DefaultID holds the default value on creation for the id field.
	technology.DefaultID = technologyDescID.Default.(func() uuid.UUID)
}
