// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/predicate"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// TechnologyDelete is the builder for deleting a Technology entity.
type TechnologyDelete struct {
	config
	hooks    []Hook
	mutation *TechnologyMutation
}

// Where appends a list predicates to the TechnologyDelete builder.
func (_d *TechnologyDelete) Where(ps ...predicate.Technology) *TechnologyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TechnologyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TechnologyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TechnologyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(technology.Table, sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TechnologyDeleteOne is the builder for deleting a single Technology entity.
type TechnologyDeleteOne struct {
	_d *TechnologyDelete
}

// Where appends a list predicates to the TechnologyDelete builder.
func (_d *TechnologyDeleteOne) Where(ps ...predicate.Technology) *TechnologyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TechnologyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{technology.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TechnologyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
