// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/project"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// TechnologyCreate is the builder for creating a Technology entity.
type TechnologyCreate struct {
	config
	mutation *TechnologyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSlug sets the "slug" field.
func (_c *TechnologyCreate) SetSlug(v string) *TechnologyCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *TechnologyCreate) SetName(v string) *TechnologyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *TechnologyCreate) SetCategory(v string) *TechnologyCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TechnologyCreate) SetCreatedAt(v time.Time) *TechnologyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TechnologyCreate) SetNillableCreatedAt(v *time.Time) *TechnologyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TechnologyCreate) SetUpdatedAt(v time.Time) *TechnologyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TechnologyCreate) SetNillableUpdatedAt(v *time.Time) *TechnologyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TechnologyCreate) SetID(v uuid.UUID) *TechnologyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TechnologyCreate) SetNillableID(v *uuid.UUID) *TechnologyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *TechnologyCreate) AddProjectIDs(ids ...uuid.UUID) *TechnologyCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *TechnologyCreate) AddProjects(v ...*Project) *TechnologyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// Mutation returns the TechnologyMutation object of the builder.
func (_c *TechnologyCreate) Mutation() *TechnologyMutation {
	return _c.mutation
}

// Save creates the Technology in the database.
func (_c *TechnologyCreate) Save(ctx context.Context) (*Technology, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TechnologyCreate) SaveX(ctx context.Context) *Technology {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechnologyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechnologyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TechnologyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := technology.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := technology.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := technology.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TechnologyCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Technology.slug"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Technology.name"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Technology.category"`)}
	}
	return nil
}

func (_c *TechnologyCreate) sqlSave(ctx context.Context) (*Technology, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TechnologyCreate) createSpec() (*Technology, *sqlgraph.CreateSpec) {
	var (
		_node = &Technology{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(technology.Table, sqlgraph.NewFieldSpec(technology.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(technology.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(technology.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(technology.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(technology.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(technology.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technology.ProjectsTable,
			Columns: technology.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectTechnologyCreate{config: _c.config, mutation: newProjectTechnologyMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Technology.Create().
//		SetSlug(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TechnologyUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *TechnologyCreate) OnConflict(opts ...sql.ConflictOption) *TechnologyUpsertOne {
	_c.conflict = opts
	return &TechnologyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Technology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TechnologyCreate) OnConflictColumns(columns ...string) *TechnologyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TechnologyUpsertOne{
		create: _c,
	}
}

type (
	// TechnologyUpsertOne is the builder for "upsert"-ing
	//  one Technology node.
	TechnologyUpsertOne struct {
		create *TechnologyCreate
	}

	// TechnologyUpsert is the "OnConflict" setter.
	TechnologyUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlug sets the "slug" field.
func (u *TechnologyUpsert) SetSlug(v string) *TechnologyUpsert {
	u.Set(technology.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TechnologyUpsert) UpdateSlug() *TechnologyUpsert {
	u.SetExcluded(technology.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *TechnologyUpsert) SetName(v string) *TechnologyUpsert {
	u.Set(technology.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TechnologyUpsert) UpdateName() *TechnologyUpsert {
	u.SetExcluded(technology.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *TechnologyUpsert) SetCategory(v string) *TechnologyUpsert {
	u.Set(technology.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TechnologyUpsert) UpdateCategory() *TechnologyUpsert {
	u.SetExcluded(technology.FieldCategory)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TechnologyUpsert) SetUpdatedAt(v time.Time) *TechnologyUpsert {
	u.Set(technology.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TechnologyUpsert) UpdateUpdatedAt() *TechnologyUpsert {
	u.SetExcluded(technology.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Technology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(technology.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TechnologyUpsertOne) UpdateNewValues() *TechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(technology.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(technology.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Technology.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TechnologyUpsertOne) Ignore() *TechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TechnologyUpsertOne) DoNothing() *TechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TechnologyCreate.OnConflict
// documentation for more info.
func (u *TechnologyUpsertOne) Update(set func(*TechnologyUpsert)) *TechnologyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *TechnologyUpsertOne) SetSlug(v string) *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TechnologyUpsertOne) UpdateSlug() *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *TechnologyUpsertOne) SetName(v string) *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TechnologyUpsertOne) UpdateName() *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *TechnologyUpsertOne) SetCategory(v string) *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TechnologyUpsertOne) UpdateCategory() *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateCategory()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TechnologyUpsertOne) SetUpdatedAt(v time.Time) *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TechnologyUpsertOne) UpdateUpdatedAt() *TechnologyUpsertOne {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TechnologyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TechnologyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TechnologyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TechnologyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TechnologyUpsertOne.ID is not supported by MySQL driver. Use TechnologyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TechnologyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TechnologyCreateBulk is the builder for creating many Technology entities in bulk.
type TechnologyCreateBulk struct {
	config
	err      error
	builders []*TechnologyCreate
	conflict []sql.ConflictOption
}

// Save creates the Technology entities in the database.
func (_c *TechnologyCreateBulk) Save(ctx context.Context) ([]*Technology, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Technology, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TechnologyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TechnologyCreateBulk) SaveX(ctx context.Context) []*Technology {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechnologyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechnologyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Technology.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TechnologyUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *TechnologyCreateBulk) OnConflict(opts ...sql.ConflictOption) *TechnologyUpsertBulk {
	_c.conflict = opts
	return &TechnologyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Technology.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TechnologyCreateBulk) OnConflictColumns(columns ...string) *TechnologyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TechnologyUpsertBulk{
		create: _c,
	}
}

// TechnologyUpsertBulk is the builder for "upsert"-ing
// a bulk of Technology nodes.
type TechnologyUpsertBulk struct {
	create *TechnologyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Technology.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(technology.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TechnologyUpsertBulk) UpdateNewValues() *TechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(technology.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(technology.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Technology.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TechnologyUpsertBulk) Ignore() *TechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TechnologyUpsertBulk) DoNothing() *TechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TechnologyCreateBulk.OnConflict
// documentation for more info.
func (u *TechnologyUpsertBulk) Update(set func(*TechnologyUpsert)) *TechnologyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TechnologyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *TechnologyUpsertBulk) SetSlug(v string) *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *TechnologyUpsertBulk) UpdateSlug() *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *TechnologyUpsertBulk) SetName(v string) *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TechnologyUpsertBulk) UpdateName() *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *TechnologyUpsertBulk) SetCategory(v string) *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TechnologyUpsertBulk) UpdateCategory() *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateCategory()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TechnologyUpsertBulk) SetUpdatedAt(v time.Time) *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TechnologyUpsertBulk) UpdateUpdatedAt() *TechnologyUpsertBulk {
	return u.Update(func(s *TechnologyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TechnologyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TechnologyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TechnologyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TechnologyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
