// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/technology"
)

// Technology is the model entity for the Technology schema.
type Technology struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TechnologyQuery when eager-loading is set.
	Edges        TechnologyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TechnologyEdges holds the relations/edges for other nodes in the graph.
type TechnologyEdges struct {
	// Projects holds the value of the projects edge.
	Projects []*Project `json:"projects,omitempty"`
	// ProjectLinks holds the value of the project_links edge.
	ProjectLinks []*ProjectTechnology `json:"project_links,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e TechnologyEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[0] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// ProjectLinksOrErr returns the ProjectLinks value or an error if the edge
// was not loaded in eager-loading.
func (e TechnologyEdges) ProjectLinksOrErr() ([]*ProjectTechnology, error) {
	if e.loadedTypes[1] {
		return e.ProjectLinks, nil
	}
	return nil, &NotLoadedError{edge: "project_links"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Technology) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case technology.FieldSlug, technology.FieldName, technology.FieldCategory:
			values[i] = new(sql.NullString)
		case technology.FieldCreatedAt, technology.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case technology.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Technology fields.
func (_m *Technology) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case technology.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case technology.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case technology.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case technology.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case technology.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case technology.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Technology.
// This includes values selected through modifiers, order, etc.
func (_m *Technology) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProjects queries the "projects" edge of the Technology entity.
func (_m *Technology) QueryProjects() *ProjectQuery {
	return NewTechnologyClient(_m.config).QueryProjects(_m)
}

// QueryProjectLinks queries the "project_links" edge of the Technology entity.
func (_m *Technology) QueryProjectLinks() *ProjectTechnologyQuery {
	return NewTechnologyClient(_m.config).QueryProjectLinks(_m)
}

// Update returns a builder for updating this Technology.
// Note that you need to call Technology.Unwrap() before calling this method if this Technology
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Technology) Update() *TechnologyUpdateOne {
	return NewTechnologyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Technology entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Technology) Unwrap() *Technology {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Technology is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Technology) String() string {
	var builder strings.Builder
	builder.WriteString("Technology(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Technologies is a parsable slice of Technology.
type Technologies []*Technology
