// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Default: schema.Expr("gen_random_uuid()")},
		{Name: "slug", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "title", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "summary", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "period", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "role", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "content_markdown", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "featured", Type: field.TypeBool, Default: false},
		{Name: "published", Type: field.TypeBool, Default: false},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "repository_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "live_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("NOW()")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("NOW()")},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "projects_published_display_order_idx",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[9], ProjectsColumns[2], ProjectsColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "published = TRUE",
				},
			},
			{
				Name:    "projects_published_featured_display_order_idx",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[9], ProjectsColumns[2], ProjectsColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "published = TRUE AND featured = TRUE",
				},
			},
		},
	}
	// ProjectTechnologiesColumns holds the columns for the "project_technologies" table.
	ProjectTechnologiesColumns = []*schema.Column{
		{Name: "display_order", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("NOW()")},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "technology_id", Type: field.TypeUUID},
	}
	// ProjectTechnologiesTable holds the schema information for the "project_technologies" table.
	ProjectTechnologiesTable = &schema.Table{
		Name:       "project_technologies",
		Columns:    ProjectTechnologiesColumns,
		PrimaryKey: []*schema.Column{ProjectTechnologiesColumns[2], ProjectTechnologiesColumns[3]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_technologies_project_fk",
				Columns:    []*schema.Column{ProjectTechnologiesColumns[2]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_technologies_technology_fk",
				Columns:    []*schema.Column{ProjectTechnologiesColumns[3]},
				RefColumns: []*schema.Column{TechnologiesColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_technologies_project_display_order_unique",
				Unique:  true,
				Columns: []*schema.Column{ProjectTechnologiesColumns[2], ProjectTechnologiesColumns[0]},
			},
			{
				Name:    "project_technologies_technology_id_idx",
				Unique:  false,
				Columns: []*schema.Column{ProjectTechnologiesColumns[3]},
			},
		},
	}
	// TechnologiesColumns holds the columns for the "technologies" table.
	TechnologiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Default: schema.Expr("gen_random_uuid()")},
		{Name: "slug", Type: field.TypeString, Unique: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "name", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "category", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, Default: schema.Expr("NOW()")},
		{Name: "updated_at", Type: field.TypeTime, Default: schema.Expr("NOW()")},
	}
	// TechnologiesTable holds the schema information for the "technologies" table.
	TechnologiesTable = &schema.Table{
		Name:       "technologies",
		Columns:    TechnologiesColumns,
		PrimaryKey: []*schema.Column{TechnologiesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		ProjectTechnologiesTable,
		TechnologiesTable,
	}
)

func init() {
	ProjectsTable.Annotation = &entsql.Annotation{
		Table: "projects",
	}
	ProjectsTable.Annotation.Checks = map[string]string{
		"projects_display_order_non_negative_check": "display_order >= 0",
	}
	ProjectTechnologiesTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectTechnologiesTable.ForeignKeys[1].RefTable = TechnologiesTable
	ProjectTechnologiesTable.Annotation = &entsql.Annotation{
		Table: "project_technologies",
	}
	ProjectTechnologiesTable.Annotation.Checks = map[string]string{
		"project_technologies_display_order_non_negative_check": "display_order >= 0",
	}
	TechnologiesTable.Annotation = &entsql.Annotation{
		Table: "technologies",
	}
}
