// Code generated by ent, DO NOT EDIT.

package projecttechnology

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projecttechnology type in the database.
	Label = "project_technology"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTechnologyID holds the string denoting the technology_id field in the database.
	FieldTechnologyID = "technology_id"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeTechnology holds the string denoting the technology edge name in mutations.
	EdgeTechnology = "technology"
	// ProjectFieldID holds the string denoting the ID field of the Project.
	ProjectFieldID = "id"
	// TechnologyFieldID holds the string denoting the ID field of the Technology.
	TechnologyFieldID = "id"
	// Table holds the table name of the projecttechnology in the database.
	Table = "project_technologies"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_technologies"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// TechnologyTable is the table that holds the technology relation/edge.
	TechnologyTable = "project_technologies"
	// TechnologyInverseTable is the table name for the Technology entity.
	// It exists in this package in order to avoid circular dependency with the "technology" package.
	TechnologyInverseTable = "technologies"
	// TechnologyColumn is the table column denoting the technology relation/edge.
	TechnologyColumn = "technology_id"
)

// Columns holds all SQL columns for projecttechnology fields.
var Columns = []string{
	FieldProjectID,
	FieldTechnologyID,
	FieldDisplayOrder,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DisplayOrderValidator is a validator for the "display_order" field. It is called by the builders before save.
	DisplayOrderValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProjectTechnology queries.
type OrderOption func(*sql.Selector)

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTechnologyID orders the results by the technology_id field.
func ByTechnologyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechnologyID, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByTechnologyField orders the results by technology field.
func ByTechnologyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechnologyStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, ProjectColumn),
		sqlgraph.To(ProjectInverseTable, ProjectFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
	)
}
func newTechnologyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, TechnologyColumn),
		sqlgraph.To(TechnologyInverseTable, TechnologyFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TechnologyTable, TechnologyColumn),
	)
}
