// Code generated by ent, DO NOT EDIT.

package projecttechnology

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/vkng1104/VK-platform/apps/api/internal/platform/persistence/ent/predicate"
)

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldProjectID, v))
}

// TechnologyID applies equality check predicate on the "technology_id" field. It's identical to TechnologyIDEQ.
func TechnologyID(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldTechnologyID, v))
}

// DisplayOrder applies equality check predicate on the "display_order" field. It's identical to DisplayOrderEQ.
func DisplayOrder(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldDisplayOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldCreatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNotIn(FieldProjectID, vs...))
}

// TechnologyIDEQ applies the EQ predicate on the "technology_id" field.
func TechnologyIDEQ(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldTechnologyID, v))
}

// TechnologyIDNEQ applies the NEQ predicate on the "technology_id" field.
func TechnologyIDNEQ(v uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNEQ(FieldTechnologyID, v))
}

// TechnologyIDIn applies the In predicate on the "technology_id" field.
func TechnologyIDIn(vs ...uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldIn(FieldTechnologyID, vs...))
}

// TechnologyIDNotIn applies the NotIn predicate on the "technology_id" field.
func TechnologyIDNotIn(vs ...uuid.UUID) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNotIn(FieldTechnologyID, vs...))
}

// DisplayOrderEQ applies the EQ predicate on the "display_order" field.
func DisplayOrderEQ(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldDisplayOrder, v))
}

// DisplayOrderNEQ applies the NEQ predicate on the "display_order" field.
func DisplayOrderNEQ(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNEQ(FieldDisplayOrder, v))
}

// DisplayOrderIn applies the In predicate on the "display_order" field.
func DisplayOrderIn(vs ...int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldIn(FieldDisplayOrder, vs...))
}

// DisplayOrderNotIn applies the NotIn predicate on the "display_order" field.
func DisplayOrderNotIn(vs ...int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNotIn(FieldDisplayOrder, vs...))
}

// DisplayOrderGT applies the GT predicate on the "display_order" field.
func DisplayOrderGT(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldGT(FieldDisplayOrder, v))
}

// DisplayOrderGTE applies the GTE predicate on the "display_order" field.
func DisplayOrderGTE(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldGTE(FieldDisplayOrder, v))
}

// DisplayOrderLT applies the LT predicate on the "display_order" field.
func DisplayOrderLT(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldLT(FieldDisplayOrder, v))
}

// DisplayOrderLTE applies the LTE predicate on the "display_order" field.
func DisplayOrderLTE(v int) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldLTE(FieldDisplayOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ProjectTechnology {
	return predicate.ProjectTechnology(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProjectColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTechnology applies the HasEdge predicate on the "technology" edge.
func HasTechnology() predicate.ProjectTechnology {
	return predicate.ProjectTechnology(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, TechnologyColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, TechnologyTable, TechnologyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTechnologyWith applies the HasEdge predicate on the "technology" edge with a given conditions (other predicates).
func HasTechnologyWith(preds ...predicate.Technology) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(func(s *sql.Selector) {
		step := newTechnologyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectTechnology) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectTechnology) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectTechnology) predicate.ProjectTechnology {
	return predicate.ProjectTechnology(sql.NotPredicates(p))
}
