// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectTechnology is the predicate function for projecttechnology builders.
type ProjectTechnology func(*sql.Selector)

// Technology is the predicate function for technology builders.
type Technology func(*sql.Selector)
